default_language_version:
  python: python3.7

default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      # Python Checks
      - id: flake8
      # Config Hooks
      - id: check-json
      - id: check-xml
      - id: check-yaml
      # General Hooks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # Git related hooks
      - id: check-merge-conflict
      - id: no-commit-to-branch
        args:
          # - "--branch=develop"
          - "--branch=master"
  - repo: https://github.com/PyCQA/pydocstyle
    rev: master
    hooks:
      - id: pydocstyle
