# Generated by Django 2.2.7 on 2019-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('checked_out', models.BooleanField(default=False)),
                ('rentee', models.CharField(max_length=30)),
            ],
        ),
    ]
