# Generated by Django 2.2.7 on 2019-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rentee',
        ),
        migrations.AddField(
            model_name='car',
            name='another_field',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
