# Generated by Django 2.2.7 on 2019-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20191108_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rentee',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
