# Generated by Django 2.2.7 on 2019-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_rentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('rentee', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='another_field',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
